import type { NextPage } from "next";
import Head from "next/head";
import Header from "../components/Header";
import Main from "../components/Main";

const Home: NextPage = () => {
  return (
    <div className="app scroll-smooth">
      <Head>
        <title>Youtube + Tailwind</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-[#212121fa] w-full h-full min-h-screen antialiased">
        <Header />
        <Main />
      </div>
    </div>
  );
};

export default Home;
